### ISSUE TITLE
Investigate intermittent issues with build pipelines

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#334] opened 2021-01-06 00:40 UTC
The Azure Devops pipelines have begun to fail intermittently with issues unrelated to changes in the pull request that triggered them. We should investigate and update to make them more resilient.

**Comment by siddhijain** [comment] 2022-02-25 16:14
Closing this since build pipeline is now moved to OneBranch. We will monitor if the same issue is reproducible there.

**Closed by siddhijain** 2022-02-25 16:14 UTC
Labels: fundamentals
