### ISSUE TITLE
Could upgrade version of oauth2-oidc-sdk for spring support?

### ISSUE THREAD

**Issue by Netyyyy** [AzureAD/microsoft-authentication-library-for-java#493] opened 2022-04-21 04:17 UTC
The version of `net.minidev:json-smart` in spring-boot:2.6.6 now is 2.4.8,
but `msal4j:1.11.3` still uses `oauth2-oidc-sdk:9.22.1` which only supports json-smart[1.3.3,2.4.7],
So when will the `oauth2-oidc-sdk` be upgraded to the latest version to support `json-smart:2.4.8`?

**Comment by siddhijain** [comment] 2022-04-21 19:17
Thanks for letting us know. We will work on updating this dependency and will update the thread once it is done.

**Comment by Netyyyy** [comment] 2022-04-28 06:48
Thanks for the help. so when the fixed version will be released?

**Comment by Avery-Dunn** [comment] 2022-05-06 19:30
This issue was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/494, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).

If the issue is still unresolved or if there are any related issues feel free to re-open this thread or open a new one.

**Closed by Avery-Dunn** 2022-05-06 19:30 UTC
Labels: backlog, Fixed
