### ISSUE TITLE
0.5.0-preview possibly released with mismatching source code/documentation?

### ISSUE THREAD

**Issue by esuomi** [AzureAD/microsoft-authentication-library-for-java#94] opened 2019-09-10 11:06 UTC
Just noticed this while testing out the new Microsoft Identity Platform 2.0 functionality, the currently released version _(0.5.0-preview)_ does not match the sources and documentation released alongside with it.

To be specific, the issue I noticed is that the class `com.microsoft.aad.msal4j.AuthorizationCodeParameters` is present in the JAR and the source released alongside makes reference to `ConfidentialClientApplication#acquireToken(AuthorizationCodeParameters)` method which however does not actually exist, the only available overloads are for `ClientCredentialParameters` and `OnBehalfOfParameters`. When viewed through IntelliJ IDEA, when opening the class `com.microsoft.aad.msal4j.ClientApplicationBase` it even puts a red alert box on top with the text _"Library source does not match the bytecode for class ClientApplicationBase"_.

To add to the confusion, this mismatch is also present in the example application at [Azure-Samples/ms-identity-java-webapp AuthHelper.java#L187-L192](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/master/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L187-L192)

**Comment by sangonzal** [comment] 2019-09-10 16:31
@esuomi thanks for taking the time to test 0.5.0-preview. 

If understand correctly, what you are seeing is that the source code on GitHub and the web app sample make a reference to `ConfidentialClientApplication#acquireToken(AuthorizationCodeParameters)`, but when you download the JAR and try to use this method it is not actually there? 

Where are you downloading the JAR and the source code from? Could you provide some steps to reproduce this behavior?

**Comment by esuomi** [comment] 2019-09-10 18:17
I downloaded the JARs direct from Maven Central, or at least I believe that's the source - whatever IntelliJ IDEA uses as default. IDEA has a direct option to download sources and documentation alongside the main dependency JAR as well, I used that, and on top of that IDEA comes with built-in decompiler which is what it uses to check that the downloaded source matches with the downloaded JAR with .class files.

And yes, you understood correctly - the sample app shows usage of a method which doesn't actually exist in the publicly released library.

**Comment by sangonzal** [comment] 2019-09-10 20:03
@esuomi I have created a project from scratch, added MSAL 0.5.0-preview as a dependency, and set IDEA to download sources and documentation. When I open up `com.microsoft.aad.msal4j.ClientApplicationBase` the first method that I can see the is `acquireToken(AuthorizationCodeParameters)`. Furthermore if I instantiate a confidential client application and try to use, it works. 

![JavaIssue](https://user-images.githubusercontent.com/35743865/64645099-fba00900-d3c8-11e9-9fc1-5f3374f6f52d.PNG)

I do also get the "Library source does not match the bytecode for class ClientApplicationBase" message, but I believe this is due to Lombok and not the issue that you are mentioning. I will look into adding a delombok step before publishing sources so we can get rid of this message, and update this thread.

**Comment by thobbs** [comment] 2019-10-03 22:01
I'd like to second what @esuomi mentioned. I also just ran into this issue trying to use the library through Clojure, where the error shows up at runtime as:

`java.lang.IllegalArgumentException: No matching method acquireToken found taking 1 args for class com.microsoft.aad.msal4j.ConfidentialClientApplication`

Do you have any recommendations for doing a manual "delombok'ed" build, or otherwise working around this?

**Comment by thobbs** [comment] 2019-10-03 22:34
So far, it looks like type-hinting as `ClientApplicationBase` avoids this error. For example:

~~~clojure
(.acquireToken ^ClientApplicationBase app                                                                                                                                
               ^AuthorizationCodeParameters params)
~~~

where `ClientApplicationBase` refers to `com.microsoft.aad.msal4j.ClientApplicationBase`.

**Comment by thobbs** [comment] 2019-10-04 18:10
I'm also seeing a similar issue where type hinting does _not_ work as a workaround. When trying to call `validateAuthority(boolean)` or `logPii(boolean)` on `ConfidentialClientApplication$Builder`, I get the following errors:

~~~
No matching method validateAuthority found taking 1 args for class com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder
~~~
~~~
No matching method logPii found taking 1 args for class com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder
~~~

**Comment by SomkaPe** [comment] 2019-10-10 01:46
looks like we used as input to maven-source-plugin sources with lombok annotations, so you get 
"Library source does not match the bytecode ... " issue, so by switching to delomboked sources we should fix it.

**Comment by sangonzal** [comment] 2019-10-10 16:23
@esuomi @thobbs #103 should fix this. We'll release 0.6.0-preview with this change and should be able to get it from Maven central either today or tomorrow to test out.

**Comment by sangonzal** [comment] 2019-10-21 16:57
@esuomi @thobbs Closing this issue. If you run into any more problem, feel free to reopen.

**Closed by sangonzal** 2019-10-21 16:57 UTC

**Comment by toburger** [comment] 2021-02-27 12:33
I'm running into this issue when trying to call  `AbstractClientApplicationBase$Builder` methods in Clojure:

Example, where I want to set the authority:
```clj
(def app
  (.. (ConfidentialClientApplication/builder client-id credential)
      (.authority authority)
      (.build)))
```

Error:
```
Reflection warning, hello.clj:36:3 - call to method .authority on com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder can't be resolved (no such method).
Reflection warning, hello.clj:36:3 - call to method .build can't be resolved (target class is unknown).
Execution error (IllegalArgumentException) at clojure.run.exec/requiring-resolve' (exec.clj:31).
No matching method .authority found taking 1 args for class com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder
```
