### ISSUE TITLE
java.lang.IllegalArgumentException: clientSecret is null or empty only on Azure Container Instance

### ISSUE THREAD

**Issue by sdebruyn** [AzureAD/microsoft-authentication-library-for-java#354] opened 2021-02-16 08:43 UTC
I am cross-linking this issue since I believe the culprit might be in this repository: https://github.com/microsoft/mssql-jdbc/issues/1517

**Comment by sangonzal** [comment] 2021-02-16 18:42
@sdebruyn Although the exception is thrown from MSAL, the issue is in mssql-jdbc. MSAL relies on the client secret being passed in from whoever is calling it. It looks like for some reason mssql-jdbc is not able to load the client secret from the environment on Azure Container Instance to pass it in to MSAL. 

Closing this issue as it's not an issue in MSAL. If you do find an issue with the library, feel free to open a separate GitHub issue.

**Closed by sangonzal** 2021-02-16 18:42 UTC
Labels: external
