### ISSUE TITLE
[Bug] Managed Identity doesn't cert thumbprint from Service Fabric MI env.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#773] opened 2024-01-10 21:11 UTC
### Library version used

14.4.2-beta

### Java version

JDK 17

### Scenario

ManagedIdentityClient - managed identity

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Currently Managed Identity doesn't read the IDENTITY_SERVER_THUMBPRINT for Service Fabric MI environment.
This cert needs to be trusted by the client to pass TLS validation when request is sent to the service fabric MI endpoint.

Azure SDK for Java logic for the same can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java#L1032)

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by Avery-Dunn** [comment] 2024-01-10 22:10
This is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/758 (which links to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4462 in the .NET repo, with more info and a proposed solution)

**Closed as completed by Avery-Dunn** 2024-01-10 22:10 UTC
