### ISSUE TITLE
Update documentation for MSI Java

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-java#792] opened 2024-02-27 17:51 UTC
Update MSI documentation here: https://github.com/Azure-Samples/msal-managed-identity/tree/main/src when the sample is ready with the link and latest updates before GA

Link to MSI Java documentation: [Managed identity with MSAL Java - Microsoft Authentication Library for Java | Microsoft Learn](https://learn.microsoft.com/en-us/entra/msal/java/advanced/managed-identity)

**Comment by bgavrilMS** [comment] 2024-03-05 18:15
Duplicate of #694

**Closed as not planned by bgavrilMS** 2024-03-05 18:15 UTC
