### ISSUE TITLE
Write MSI Sample

### ISSUE THREAD

**Issue by DidunAyodeji** [AzureAD/microsoft-authentication-library-for-java#793] opened 2024-02-27 18:08 UTC
Write MSI sample for Java based on the .NET sample

**Comment by neha-bhargava** [comment] 2024-02-27 18:23
The Sample can be added to a folder called Java here: https://github.com/Azure-Samples/msal-managed-identity/tree/main/src/dotnet

**Comment by bgavrilMS** [comment] 2024-03-05 18:13
Duplicate of #693

**Closed as not planned by bgavrilMS** 2024-03-05 18:13 UTC
Labels: Samples
