### ISSUE TITLE
Newer version of com.nimbusds:oauth2-oidc-sdk still needed for spring-boot 2.4 to work

### ISSUE THREAD

**Issue by larzza** [AzureAD/microsoft-authentication-library-for-java#348] opened 2021-02-03 20:15 UTC
<details><summary>Stack-trace</summary>
Caused by: java.lang.NoSuchMethodError: com.nimbusds.jwt.JWTClaimsSet.toJSONObject()Lnet/minidev/json/JSONObject;
	at com.nimbusds.oauth2.sdk.auth.JWTAuthenticationClaimsSet.parse(JWTAuthenticationClaimsSet.java:166) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.JWTAuthentication.<init>(JWTAuthentication.java:139) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.<init>(PrivateKeyJWT.java:251) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.parse(PrivateKeyJWT.java:286) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.createClientAuthFromClientAssertion(ConfidentialClientApplication.java:97) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.buildValidClientCertificateAuthority(ConfidentialClientApplication.java:89) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.initClientAuthentication(ConfidentialClientApplication.java:66) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:56) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:32) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.build(ConfidentialClientApplication.java:144) ~[msal4j-1.9.0.jar:1.9.0]
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301) ~[kafka-clients-2.6.0.jar:na]
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574) ~[na:na]
	at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158) ~[kafka-clients-2.6.0.jar:na]
	... 8 common frames omitted
</details>

`./gradlew dependencies` reveals transitive dependencies  to `com.nimbusds:nimbus-jose-jwt` from `com.microsoft.azure:msal4j`.
</details>

Like so:

```
+--- com.microsoft.azure:msal4j:1.9.0
|    +--- com.nimbusds:oauth2-oidc-sdk:8.23.1
|    |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |    +--- com.nimbusds:content-type:2.1
|    |    +--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3
|    |    |    \--- net.minidev:accessors-smart:1.2
|    |    |         \--- org.ow2.asm:asm:5.0.4
|    |    +--- com.nimbusds:lang-tag:1.4.4
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.18 -> 9.1.3
|    |         \--- com.github.stephenc.jcip:jcip-annotations:1.0-1
```

 `com.microsoft.azure:msal4j:1.9.0` -> `com.nimbusds:oauth2-oidc-sdk:8.23.1` ->  `com.nimbusds:nimbus-jose-jwt:8.18`

But we get `com.nimbusds:nimbus-jose-jwt:9.13`, I assume because of upgraded dependencies in Springboot 2.4 

- In `com.nimbusds:nimbus-jose-jwt:8.18`: `public static JWTClaimsSet parse(final JSONObject json)`
- In  `com.nimbusds:nimbus-jose-jwt:9.1.3`:  `public static JWTClaimsSet parse(final Map<String, Object> json)`

Conclusion: `msal4j` need a newer dependency to `com.nimbusds:oauth2-oidc-sdk` than `8.23.1`.

https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/322#issuecomment-772396594

**Comment by Avery-Dunn** [comment] 2021-02-04 22:01
Hello @larzza : It seems the issue is the versions of `oauth2-oidc-sdk` and `nimbus-jose-jwt` that Spring Boot 2.4 uses. Springboot 2.4 uses `oauth2-oidc-sdk` 8.23.1, which expects version 8.18 of `nimbus-jose-jwt`, but it also uses version 9.1.3 of  `nimbus-jose-jwt`, and these versions of `nimbus-jose-jwt` have some incompatibility. 

There are situations where out library calls methods from `oauth2-oidc-sdk`, and those methods internally make calls to `nimbus-jose-jwt`, but due to there being some some breaking changes between the version Spring Boot 2.4 uses and the version `oauth2-oidc-sdk` 8.23.1 expects our library is seeing some exceptions when using Spring Boot 2.4 (such as from the changed return type for the `toJSONObject` method mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/322#issuecomment-771906918). This issue only appeared with Spring Boot 2.4 because previous versions of Spring Boot didn't call for a specific version of `nimbus-jose-jwt`.

We're currently looking into the changes needed to be fully compatible with the versions of `oauth2-oidc-sdk` and `nimbus-jose-jwt` that Spring Boot uses, and I will update this thread with the changes/release time once we've sorted it out.

**Comment by larzza** [comment] 2021-02-05 07:35
Thanks @Avery-Dunn!

Looking forward to be able to use Spring Boot 2.4! :-)

**Comment by baidehig** [comment] 2021-02-15 17:01
Hi @Avery-Dunn : I am using a Spring 5.2.3 Application where I added oauth2-oidc-sdk (9.1) and MSAL (1.9).

I am getting below error while running my java client to get the bearer token.
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/nimbusds/common/contenttype/ContentType
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/common/contenttype/ContentType

Is it a known issue? Could you suggest a solution!

**Comment by Avery-Dunn** [comment] 2021-02-23 23:18
Hello @larzza : It seems that the latest version of Spring Boot (2.4.3) has the correct dependencies that `oauth2-oidc-sdk` expects, and as part of [their release notes](https://github.com/spring-projects/spring-boot/releases/tag/v2.4.3) they list this dependency weirdness as a fixed bug. Are you able to either upgrade to 2.4.3 or downgrade to 2.4.1? Because it seems like this dependency issue will only be in version 2.4.2 of Spring, we likely won't be following through with changes to our library to accommodate what is (hopefully) a one-off bug outside of our library.

Hello @baidehig : Your issue isn't related to what this thread is about, but it has the same basic cause: MSAL Java uses version 8.23 of `oauth2-oidc-sdk`, so if you added version 9.1 of `oauth2-oidc-sdk` then there's bound to be classes/methods/constants/etc. that our library expects to find which are not in that version of `oauth2-oidc-sdk`.  Are you able to downgrade `oauth2-oidc-sdk` in your project to version 8.x?

**Comment by larzza** [comment] 2021-02-24 06:24
Hi @Avery-Dunn , yes I can confirm that the issue is gone when upgrading to Spring Boot 2.4.3.

Thanks!

With msal4j 1.9.0 and spring-boot 2.4.3 the gradle dependency graph confirms the downgraded version of the `nimbus-jose-jwt` dependency.

```
./gradlew dependencies | grep com.nimbusds:nimbus-jose-jwt
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.20.1 -> 8.20.2
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.20.1 -> 8.20.2
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.20.1 -> 8.20.2
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.20.1 -> 8.20.2
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.20.1 -> 8.20.2 
```

**Comment by baidehig** [comment] 2021-02-24 17:45
Hi @Avery-Dunn 
Thanks, it worked with the older JAR(8.23). 

Apologies for the comment in the incorrect thread.

**Comment by Avery-Dunn** [comment] 2021-02-25 01:56
@larzza and @baidehig : Sounds good, glad to hear everything is working!

We still might make the changes to support Spring Boot 2.4.2 in case someone definitely needs it, but I'm closing this thread since the library seems to be working fine on other Spring versions. If y'all have any other related issues/questions, feel free to leave a comment or re-open this thread

**Closed by Avery-Dunn** 2021-02-25 01:56 UTC
Labels: bug, question
