### ISSUE TITLE
Documentation link in README.md is invalid

### ISSUE THREAD

**Issue by JohannesPertl** [AzureAD/microsoft-authentication-library-for-java#503] opened 2022-05-04 13:46 UTC
This link can't be found: https://aka.ms/aaddevv2

**Comment by Avery-Dunn** [comment] 2022-05-06 19:19
This issue was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/504, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).

If the issue is still unresolved or if there are any related issues feel free to re-open this thread or open a new one.

**Closed by Avery-Dunn** 2022-05-06 19:19 UTC
Labels: bug, Fixed
