### ISSUE TITLE
Could not authenticate via Azure Directory Interactive with MFA

### ISSUE THREAD

**Issue by luedi** [AzureAD/microsoft-authentication-library-for-java#492] opened 2022-04-20 15:57 UTC
I want to login to an Azure SQL Server managed instance via Azure Directory Interactive. The account has MFA via Microsoft Authenticator enabled. The login screen (https://uniper-onmicrosoft-com.access.mcas.ms/aad_login) is displayed and I enter my credentials and approve them with the Microsoft authenticator app. After a while i get the response:

`The specified database user/password combination is rejected: Fehler beim Authentifizieren des Benutzers "xxx@yyy" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server`

I'm using Jetbrains DataGrip and am in contact with their support for a while. We have tried many different configuration settings but nothing worked. At least we checked the connection with a simple Java program with no other dependencies. The support guy at Jetbrains could not find any reason for the issue in DataGrip and now guess that there is a problem in the authentication library.

With Sql Server Management Studio login works fine.

I didn't find something related here. Does anyone have an idea why this occurs?

**Comment by Avery-Dunn** [comment] 2022-04-20 19:17
Hello @luedi : Is there any more to that error message, like an error code, files/line numbers for the package that threw the error, etc.? If so, could you provide it?

Also, could you describe how you're using MSAL Java in your application? You mentioned you're trying to access an Azure SQL server ([this](https://docs.microsoft.com/en-us/azure/azure-sql/database/sql-database-paas-overview), right?), and you're connecting to it using Jetbrains DataGrip but having a problem? And by "With Sql Server Management Studio login works fine", you mean you can connect to the Azure SQL server using Server Management Studio, but not with DataGrip?

**Comment by luedi** [comment] 2022-04-21 18:22
To be more precise: MFA-login via Azure Active Directory Interactive is possible with SSMS. I can login and work with the database. It's a Java problem. Jetbrains support sent me a testl program which shows the same behavior as DataGrip.

[Test-MS-ActiveDirectoryInteractive-master.zip](https://github.com/AzureAD/microsoft-authentication-library-for-java/files/8533631/Test-MS-ActiveDirectoryInteractive-master.zip)

DataGrip itself uses the follwing files:
![image](https://user-images.githubusercontent.com/12098314/164522417-f430c4f8-8ffb-4a9f-b200-0ba65a9bc875.png)

The difference in the login process is that in SSMS a modal dialog and in DataGrip a Web-Browser window is shown for entering the password. I have enabled the JDBC log in DataGrip. Here is the, anonymized, log file:

[driver-0-0.zip](https://github.com/AzureAD/microsoft-authentication-library-for-java/files/8534061/driver-0-0.zip)

Hope that helps.

**Comment by Avery-Dunn** [comment] 2022-04-25 17:15
That "No Authorization code was returned from the server" error message is thrown whenever we simply get no response (or an empty response) from the authorization server so it can be tricky to pinpoint the exact issue, especially when MSAL Java is just a dependency of some other program.

Is your Azure SQL Server or your Azure Active Directory running in a specific Azure region? I've seen that error message get thrown when the region isn't correctly discovered or there is some mismatch with authority/region/etc.

Also, I remember an issue from last year, https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/391, with a similar error message, and it seemed like the root cause for that wasn't with MSAL Java itself. The person who opened up that issue later opened another issue, https://github.com/microsoft/mssql-jdbc/issues/1586, in the mssql-jdbc repo, so you may be able to try asking there as well or seeing if this issue has already been reported.

**Comment by David-Engel** [comment] 2022-04-26 19:27
From the log file you uploaded, it looks like your interactive authentication session is simply timing out after 2 minutes. How long does it take from the time the browser pops up to the time the browser tells you to go back to your application?

2022-04-21T18:02:29.638818700Z
com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo
ConnectionID:1 ClientConnectionId: 78514320-a136-4715-ade0-49d968f1db55 FedAuthInfoData: https://login.windows.net/DB8E2F82-8A37-4C09-B7DE-ED06547B5A20

2022-04-21T18:**_02:29_**.681344900Z
com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenInteractive
java.util.logging.Logger@20be02d9Interactive authentication

2022-04-21T18:**_04:29_**.037038Z
com.intellij.database.remote.jdbc.helpers.RemoteLogHelper$LogWriter.toLog
SQLState(null) vendor code(0)

2022-04-21T18:04:29.039509700Z
com.microsoft.sqlserver.jdbc.SQLServerException.logException
SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server

From the driver side, the database tells it to use https://login.windows.net/DB8E2F82-8A37-4C09-B7DE-ED06547B5A20 to authenticate. The driver calls MSAL, directing it to that URL to get a token for the resource/database and simply waits for a response.
https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java#L140

**Comment by luedi** [comment] 2022-04-27 16:56
The "Continue" button appears right after I have authenticated myself via the Microsoft Authenticator app. Could it be that there is a misonfiguration in Azure?

**Comment by kimpenhaus** [comment] 2022-05-02 12:12
I am having the same issue - also with JetBrains DataGrip which is built on top of mssql-jdbc and msal4j. Right after the login and granting permissions to the app, there ist an redirect to localhost:xxxx which is failing on my side even though there ist something listen to that port:

redirect:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/575109/166231575-f7f7a383-84b8-40b1-9b87-2f20c9f640ee.png">

allocated ports:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/575109/166231609-f59c70b2-c08c-400d-978b-fae7be1d0495.png">

**Comment by charlesmln** [comment] 2022-05-02 16:27
I have been experiencing exactly the same and discovered that this issue occurs when the Windows language is not set to English US. If I set Windows language to French, I experience exactly the same as you. If I set windows language to English US, this works. I see you are configured in German, so it is probably the same. There is a bug somewhere in the library related to the language setting of the host.

**Comment by kimpenhaus** [comment] 2022-05-03 05:41
@charlesmln man you're genious 👍🏼 changed my language to english and indeed it is working - thanks a lot!

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/575109/166408918-7c7dd4fd-3460-4e43-980c-b501673a17f3.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/575109/166408956-fc586f76-c918-43f4-832d-1029b2f955c3.png">

**Comment by luedi** [comment] 2022-05-03 19:34
Same for me. If I change the Windows language to English, i can connect to the database.
@charlesmln Do you know, if an issue exists for this? I don't want to change the Windows language just for a single application. And i think this is definetly a bug which should be fixed.

**Comment by Avery-Dunn** [comment] 2022-05-06 19:21
Thanks everyone for the information about the issue/workaround involving language settings. We're working on figuring out exactly where the root cause of the issue is (in MSAL, JDBC, SQL Server, etc.) and I'll update this thread once we have more info.

**Comment by tkyc** [comment] 2022-05-25 21:23
I was experimenting with the interactive login and possibly narrowed the issue down to the mssql-jdbc driver as the culprit. When I tested out interactive login solely with msal4j, and changing my system's language to something like German, I didn't encounter any errors. So, msal4j doesn't seem like the one to blame here as it was working for me regardless of system language. However, I managed to reproduce the error `No Authorization code was returned from the server` using the driver + msal4j on German, which leads me to suspect the mssql-jdbc driver as the cause (fyi, driver + msal4j on English worked).

I've attached the repro code, if anyone is interested (you'll need to provide your own credentials eg. azure app id, conn string, authority etc)
[standalone.zip](https://github.com/AzureAD/microsoft-authentication-library-for-java/files/8774597/standalone.zip)

**Comment by Avery-Dunn** [comment] 2022-05-27 21:31
Based on what @tkyc said and my own similar results, it seems like the root cause of the issue is probably on the mssql-jdbc side of things and not msal4j.

I've just opened an issue in the mssql-jdbc repo (https://github.com/microsoft/mssql-jdbc/issues/1839) to try to keep better track of this issue and its resolution, and am closing this one. If anyone has more info or if it seems like the problem could be here, feel free to leave a comment and/or re-open this thread.

**Closed by Avery-Dunn** 2022-05-27 21:31 UTC
Labels: bug

**Comment by Avery-Dunn** [comment] 2022-06-30 16:46
Just an update for anyone experiencing this issue: as shown through some investigation in https://github.com/microsoft/mssql-jdbc/issues/1839, part of this problem was in the way MSAL Java handle responses, where some information was being dropped due to localization. This issue was fixed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/511 and is in the version 1.13 release, so updating to 1.13 should fix this system language problem.
