### ISSUE TITLE
How to use claims in acquireToken and acquireTokenSilently methods?

### ISSUE THREAD

**Issue by javate** [AzureAD/microsoft-authentication-library-for-java#386] opened 2021-05-07 17:39 UTC
I am working on Authorization Code Flow. So, basically I use three main `Parameters` class:

- `AuthorizationRequestUrlParameters`: For generating popup url.
- `AuthorizationCodeParameters`: For acquireToken method
- `SilentParameters`: For acquireTokenSilently method  

I implement general feature. However I have some questions about `claims`.

I saw that `claims` is passed as `claimsChallange` when getting authorization request url with `AuthorizationRequestUrlParameters `in `msal-java-webapp-sample` project . You can see it here: [https://github.com/Azure-Samples/ms-identity-java-webapp/blob/master/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L171](url)

So, should we keep this `claims` for using it in `acquireToken` and `acquireTokenSilently` methods like below?(If yes, why the above sample project doesn't use it for `acquireToken `or `acquireTokenSilently` methods?)

For `acquireToken`:
```
AuthorizationCodeParameters authorizationCodeParameters = AuthorizationCodeParameters.builder(authCode, new URI(currentUri)).claims(ClaimsRequest.formatAsClaimsRequest(claims)).build();
confidentialClientApplication.acquireToken(authorizationCodeParameters);
```
For `acquireTokenSilently`:
```
SilentParameters parameters = SilentParameters.builder(scopes, account).claims(ClaimsRequest.formatAsClaimsRequest(claims)).forceRefresh(true).build();
confidentialClientApplication.acquireTokenSilently(parameters);
```

Or are these `claims` different from the used one in `AuthorizationRequestUrlParameters` ? Then when and how should we use `claims` for `acquireToken` and `acquireTokenSilently`, is there any example implementation?

**Comment by Avery-Dunn** [comment] 2021-05-12 00:24
Hello @javate : All claims that you set as part of a request ultimately get merged together, however there are two main situations where you would need to use them:
 - Claims challenge: when making a request, the token service may return a [claims challenge](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-conditional-access-dev-guide#complying-with-a-conditional-access-policy) depending on the [conditional access policies](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-conditional-access-dev-guide) on your application/tenant/etc., and if it does then the library will throw an [MsalServiceException](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/MsalServiceException.java). If the cause of the exception was a claims challenge, then the `claims` field of the exception should be a String of some claims. To get the request to work, you just need to put those claims into the `claimsChallenge` field and retry the request.
 - Custom claims: the `claims` field is intended for you you be able to request any arbitrary claims you want, and is mainly used for requesting certain [optional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) that the token service may be able to provide, or [custom claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-claims-customization) that you set up in your application. 

Basically, a 'claims challenge' is just a specific situation where claims need to be set. I didn't write the original code in the sample you linked (I just refactored it), but I believe the intention is to simply grab whatever claims may have already been added to the request (just in case there were any?) and forward them when redirecting to the auth request URL. 

In general though, you'll only need to add claims to one of the parameter builders if your request fits one of the situations I described above: either you get some claims as part of a claims challenge (in which case you just grab them from the exception), or you know ahead of time that you'll want some optional or custom claims in the tokens you're requesting. Claims in a silent request will only be relevant if a new token is retrieved as part of the silent request (otherwise the cached token should work or you'll get a claims challenge).

**Comment by javate** [comment] 2021-05-20 12:17
@Avery-Dunn thanks. 
In my case, my reqistered application work as a multitenant application. So, the users that will give consent to my application will be in different tenants and they need to be global admin of their tenants, just for your info.

I will not set any claims in my application or my tenant. So the custom claims option does not applicable for my case, right?

For claims challange option, does this claims set in customer tenants or the tenant of the registered application?

If the claims set in the customer tenants. I will not aware the claims challange until getting an exception either making a acquireToken or acquireTokenSilently request, right? And if I get an exception with not empty claims field, then can I use this claims field to rebuild Parameter class and making a second acquireToken/acquireTokenSilently request? Or should I generate a popup url with claims challange field is filled with claims of the exception?

If I rebuild the Parameter class with claims that provided in exception field and send a second request, what will happen? 
the claims problem is simply gone? Or User prompted with a redirection automatically for the claims?

**Comment by Avery-Dunn** [comment] 2021-05-24 16:38
@javate : Yeah, if you aren't setting any custom claims in your application/tenant in Azure then you shouldn't need to worry about setting them in your app (most are for some pretty specific info, and most people won't ever need to deal with them).

As for knowing what the claims challenge will be, you may be able to know in advance based on what Azure features are used by the application/tenant. For example, [continuous access evaluation](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation) is application/resource specific, so a claims challenge for one user should be the same for another user if they're accessing the same resources. However, I don't know if the Azure folks have documented what their claims challenges typically consist of (I haven't been able to find any at least), so you may need to always handle the claims challenge exception for the first user who tries to access some resource.

As for claims challenge behavior, you're correct: if you get an exception with a non-empty claims field, then you should be able to just rebuild the parameters class with those claims and retry the request. What will happen next will depend on what the user has already consented to. I'm not too experienced with dealing with claims challenges so I'm not 100% sure of this behavior, but this is how other claims requests are handled so it should be similar: if the user has consented to the claims before (i.e., in some other request) then you should just get the AuthenticationResult, but if they haven't consented already then they should get some interactive prompt that will ask them to approve it.

**Comment by javate** [comment] 2021-06-02 18:11
@Avery-Dunn Thanks. 

For claims challange, I understood that it is resource specific. Could you give an example what is a resource? For example is `https://graph.microsoft.com` a resource? If yes, I think,`https://graph.microsoft.com` does not require a claims challange since I don't give any claimsChallange parameter and I can get successfully the `AuthenticationResult` object for some Graph API scopes. So that is proof of the `https://graph.microsoft.com` doesn't require any claims challange for all type of users, right? If so, we can check the resources that we will use by simply testing it without sending any claimsChallange and verify that we can get the AuthenticationResult, right? 

Also, lets get an exception with a non-empty claims field in our first acquireToken request. Then we make another second request with claims field. There are two option:

- if the user has consented to the claims before, we can get the AuthenticationResult.
- if user haven't consented already, then will we get a second exception or a redirection occurred automatically? 

if we get a second exception than I think We need to create `AuthorizationRequestUrlParameters` by filling its claimsChallange with the claims field of the first exception and make a redirection to that AuthorizationRequestUrl manually right?

**Comment by Avery-Dunn** [comment] 2021-06-03 20:57
@javate : I can't remember where I heard this description, but a resource is basically just something that receives an access token, such as a web API. I'm not sure if `https://graph.microsoft.com` itself is considered a resource, but [other endpoints](https://docs.microsoft.com/en-us/graph/overview#popular-api-requests) on that basic URL like `https://graph.microsoft.com/v1.0/users` or `https://graph.microsoft.com/v1.0/me` certainly are, since they need an access token to get info or do something (try going to one of those in your browser, you should get an 'access token is empty' error). 

For some of those endpoints, either no claims or some default claims are all that's needed, and for others you will need to specific specific claims or scopes in order to get a valid access token for that resource (the [/.default scope](https://graph.microsoft.com/v1.0/me) can usually be used to help get whatever the user needs to consent to). Your understanding about needed claims is correct: unless there is a change in permissions server-side, the claims needed to access a resource will always be the same.

As for your second question, I think your understanding is correct: if you get a claims challenge, you should be able to just send them as part of a new request in whatever flow you're using to get tokens for your users (`AuthorizationRequestUrl` or otherwise), and now that the token request has the correct claims then it should work.

**Comment by javate** [comment] 2021-06-04 13:11
@Avery-Dunn thanks. Could you please give me an example resourece that requires claims? I want to test it.

**Comment by Avery-Dunn** [comment] 2021-06-04 17:10
@javate : The document you linked is more correct, claims challenges will come from the resource/API when you try to use an access token, rather than when you request an access token (since the token service wouldn't know if the token request won't actually work).

I don't know off the top of my head of any common resource that requires claims, and can't find any docs with a list of them for public testing. However, most of the use cases for claims (or at least a claims challenge) are for complying with [conditional access policies](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-conditional-access-dev-guide). So, if you're an admin in your Azure AD you should be able to set [some of them](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-policy-common) up (like [MFA](https://docs.microsoft.com/en-us/azure/active-directory/authentication/tutorial-enable-azure-mfa) or [location restrictions](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/location-condition)) to get claims challenges when using APIs in your apps where those policies are enabled.

**Comment by javate** [comment] 2021-06-04 20:04
@Avery-Dunn Thanks a lot.
However this [document](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-java#conditional-access-and-claims-challenges) says different from the last one I shared above. It is said that "When getting tokens silently, your application may receive errors when a Conditional Access claims challenge such as MFA policy is required by an API you're trying to access.". I am very confused.

Yes, I have two tenant. I am Global Admin of both of them. I used one of them for registering client application and I used the other of them for giving consent to that client application like a customer tenant user for testing purpose.
So, which tenant should I use to set some conditional access policies? The tenant that has registered client application or the tenant that is used for giving consent to that client application like customer tenant?

**Comment by Avery-Dunn** [comment] 2021-06-10 21:45
@javate : I think that document is saying that if you try to get a token silently, you may get a claims challenge when the silent call tries to refresh the token if the new tokens wouldn't have the right access level. Basically, a silent call that refreshes tokens can fail for all the same reason as any other flow, since refreshing tokens just means getting a new set of tokens that have the same permissions as the old ones. 
- As an example, imagine you made a request to some resource and got the tokens you need to do it. You use the tokens a couple times successfully, but at some point the access token expires, and before you try to use it again and refresh it some conditional access policies are changed in the app/API/tenant/etc. The next silent request using that token will try to refresh it and get a new set of tokens, but will fail because it doesn't have the right claims. The silent call will then return an error with a claims challenge, just like if you tried to get the token in a non-silent flow.

As for how conditional access works with your tenant set up, the policies should be in the tenant where you registered the apps. When you set up conditional access policies you can assign them to specific apps, users, and groups in that tenant (here's an [MFA example](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa) that shows where those settings are).

**Comment by Avery-Dunn** [comment] 2021-06-18 15:54
Closing due to inactivity. If you have any more questions or issues, feel free to leave a comment or re-open.

**Closed by Avery-Dunn** 2021-06-18 15:54 UTC
Labels: question
